### ISSUE TITLE
Species parameter question

### ISSUE THREAD

**Issue by sixingchen718** [mhammell-laboratory/TEpeaks#6]
Hello
The arguments - --species=STRING  just mm9, does that means when I mapping I must use mm9, is that OK I mapping use mm10 to get the BAM file then I use TEpeaks use    -s mm?

**Comment by olivertam** [comment]
Hi,

Yes, you can use `-s mm` for mm10. The parameter helps define the effective genome size, which should not be that different between mm9 and mm10.

Thanks.

**Comment by sixingchen718** [comment]
@olivertam Thank you for your quick response. that's very helpful.

Best.
